variable "count" {
  description = "The number of target hosts to connect to"
  type        = number
  default     = 0
}

variable "ips" {
  description = "The hostnames or addresses of the vms to connect to"
  type        = list(string)
}

variable "ssh_user" {
  description = "The name of the ssh user for the target hosts"
  type        = string
  default     = "centos"
}

variable "ssh_private_key" {
  description = "The ssh private key path for the ssh access key for the target hosts"
  type        = string
}

variable "tmp_path" {
  description = "The directory to use for executing terraform scripts"
  type        = string
  default     = "/var/tmp"
}

variable "bastion_ip" {
  description = "The hostname or address of the bastion server (if needed)"
  type        = string
  default     = null
}

variable "bastion_ssh_user" {
  description = "The name of the bastion host ssh user"
  type        = string
  default     = null
}

variable "bastion_ssh_private_key" {
  description = "The ssh private key path for the ssh access key for the bastion host"
  type        = string
  default     = null
}

variable "ssh_user_sudo_password" {
  description = "The sudo password if needed"
  type        = string
  default     = ""
}

variable "sudo_cmd" {
  description = "The commnad to call for sudo"
  type        = string
  default     = "sudo"
}

variable "script" {
  description = "A string of command to execute on the target hosts, normally generated by a templatefile"
  type        = string
}

variable "working_folder" {
  description = "The working folder for the script to run from"
  type        = string
  default     = "script_connect"
}

variable "module_depends_on" {
  description = "List of modules or resources this module depends on."
  type        = list(any)
  default     = []
}
